name: spotlas_demo
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed_annotation: any
  http: ^0.13.4
  flutter_riverpod: ^1.0.4
  riverpod: ^1.0.3
  cached_network_image: ^3.2.1
  readmore: ^2.2.0
  flutter_screenutil: ^5.5.3+2
  font_awesome_flutter: any
  timeago: ^3.2.2
  carousel_slider: ^4.1.1
  like_button: ^2.0.4
  pull_to_refresh_flutter3: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  freezed: any
  json_serializable: any
  json_annotation: any


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\img\Heart-Border.svg
    - assets\img\Heart.svg
    - assets\img\Map-Border.svg
    - assets\img\Options.svg
    - assets\img\Paper-Plane-Border.svg
    - assets\img\Speech-Bubble-Border.svg
    - assets\img\Star-Border.svg
    - assets\img\Star.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
